/*******************************************************************************
File Name:      04_appD_elasticity.do
Creator:        John Iselin
Date Update:    January 2026

Purpose:        Calculate participation and mobility elasticities for Appendix D
                Based on CalEITC treatment effects from triple-difference design.

ELASTICITY FORMULAS:
================================================================================

PARTICIPATION ELASTICITY (extensive margin):
    E_part = (deltaP / P) / (delta(1-atr) / (1-atr))

    Where:
    - deltaP = DiD coefficient on employment outcome
    - P = baseline employment rate (treated group, pre-period)
    - delta(1-atr) = DiD coefficient on net-of-tax rate change
    - (1-atr) = baseline net-of-tax rate (treated group, pre-period)

    Interpretation: % change in employment per 1% change in net-of-tax rate

MOBILITY ELASTICITY (intensive margin):
    E_mob = ln(P + beta) - ln(P) / [ln|n_post - n_alt| - ln|n_pre - n_alt|]

    Where:
    - beta = treatment effect on employment transition
    - P = baseline probability
    - n_post, n_pre = net-of-tax earnings at CalEITC kink (post/pre CalEITC)
    - n_alt = net-of-tax earnings at alternative work level (FT at min wage or $27K)

    Interpretation: Proportional employment response to net-of-tax earnings differential

Inputs:
- ${data}final/acs_working_file.dta: Main analysis dataset
- ${data}eitc_parameters/caleitc_max_inc_max_cred.xlsx: CalEITC parameters
  (generated by 02b_caleitc_param_gen.do)

Outputs:
- Appendix D tables with elasticity estimates
- Sensitivity analysis across specifications

Project: CalEITC Labor Supply Effects
*******************************************************************************/

** Start log file
capture log close log_04
log using "${logs}04_appD_elasticity_${date}", name(log_04) replace text

** =============================================================================
** SECTION 1: Configuration
** =============================================================================

** Control variables for regression specifications
local controls "education age_bracket minage_qc race_group hispanic hh_adult_ct"

** Cluster variable for standard errors
local clustervar "state_fips"

** Fixed effects specification (triple-difference)
** State FE + Year FE + QC FE + all two-way interactions
local fe_base "qc_ct year state_fips"
local fe_twoway "state_fips#year state_fips#qc_ct year#qc_ct"
local did "`fe_base' `fe_twoway'"

** Time-varying state controls interacted with QC
local state_controls "c.state_unemp#i.qc_ct c.minwage#i.qc_ct"

** =============================================================================
** SECTION 2: Load and Prepare Data
** =============================================================================

di "LOADING DATA AND PREPARING SAMPLE"

** Load analysis sample
use if female == 1 & ///
       married == 0 & ///
       in_school == 0 & ///
       inrange(age, 20, 50) & ///
       citizen_test == 1 & ///
       inrange(year, 2012, 2017) ///
    using "${data}final/acs_working_file.dta", replace

** Restrict to low-education sample (HS or less)
keep if education <= 3

** Keep California and control states only
keep if state_status > 0

** Create treatment indicators
gen ca = (state_fips == 6)
gen post = (year >= 2015)
gen treated = (ca == 1 & qc_present == 1 & post == 1)
label var ca "California indicator"
label var post "Post-CalEITC period (2015+)"
label var treated "Treated: CA x QC>=1 x Post"

** Create interaction for child x year x CA (for FE)
gen childXyearXca = cond(qc_present == 1 & ca == 1, year, 2014)

** Rename state minimum wage for clarity
gen minwage = mean_st_mw
label var minwage "State minimum wage"

** Label key outcome and treatment variables
label var taxsim_sim3_atr_st "After-tax rate at CalEITC kink point"
label var part_time_y "Part-time employment indicator"
label var full_time_y "Full-time employment indicator"

** Sample size
qui count
local N = r(N)
di _n "Analysis sample: `N' observations"

** =============================================================================
** SECTION 3: Participation Elasticity - Baseline Estimates
** =============================================================================

di _n "=" * 70
di "PARTICIPATION ELASTICITY CALCULATIONS"
di "=" * 70

** -----------------------------------------------------------------------------
** Step 3.1: Calculate baseline net-of-tax rate (denominator component)
** -----------------------------------------------------------------------------

di _n "Step 3.1: Baseline net-of-tax rate"
di "-" * 40

** Mean after-tax rate for treated group in pre-period
qui summ taxsim_sim3_atr_st if qc_present == 1 & ca == 1 & post == 0 [aw = weight]
local atr_pre = r(mean)
local netoftax_pre = 1 - `atr_pre'
di "  Mean ATR (treated, pre): " %6.4f `atr_pre'
di "  Net-of-tax rate (1-ATR): " %6.4f `netoftax_pre'

** -----------------------------------------------------------------------------
** Step 3.2: Estimate change in net-of-tax rate (DiD on ATR)
** -----------------------------------------------------------------------------

di _n "Step 3.2: DiD estimate of ATR change"
di "-" * 40

qui reghdfe taxsim_sim3_atr_st treated [aw = weight], ///
    absorb(`did') vce(cluster `clustervar')

local delta_atr = _b[treated]
local delta_netoftax = -1 * `delta_atr'  // Change in (1-ATR)
local se_atr = _se[treated]

di "  DiD coefficient on ATR: " %8.5f `delta_atr' " (SE: " %8.5f `se_atr' ")"
di "  Change in net-of-tax rate: " %8.5f `delta_netoftax'

** Calculate denominator for elasticity formula
local denom = `delta_netoftax' / `netoftax_pre'
di _n "  DENOMINATOR = delta(1-ATR)/(1-ATR) = " %8.5f `denom'

** -----------------------------------------------------------------------------
** Step 3.3: Baseline employment rate (numerator component)
** -----------------------------------------------------------------------------

di _n "Step 3.3: Baseline employment rate"
di "-" * 40

qui summ part_time_y if qc_present == 1 & ca == 1 & post == 0 [aw = weight]
local P_base = r(mean)
di "  Part-time employment rate (treated, pre): " %6.4f `P_base'

** -----------------------------------------------------------------------------
** Step 3.4: DiD estimate of employment change
** -----------------------------------------------------------------------------

di _n "Step 3.4: DiD estimate of employment change"
di "-" * 40

qui reghdfe part_time_y treated `state_controls' [aw = weight], ///
    absorb(`did' `controls') vce(cluster `clustervar')

local beta_pt = _b[treated]
local se_pt = _se[treated]

di "  DiD coefficient (part-time): " %8.5f `beta_pt' " (SE: " %8.5f `se_pt' ")"

** -----------------------------------------------------------------------------
** Step 3.5: Calculate participation elasticity
** -----------------------------------------------------------------------------

di _n "Step 3.5: Participation Elasticity"
di "-" * 40

** Using margins for proper standard error calculation
margins, expression((_b[treated] / `P_base') / (`denom')) post
mat results = r(table)
local e_part = results[1,1]
local e_part_se = results[2,1]
local e_part_lb = results[5,1]
local e_part_ub = results[6,1]

di "  PARTICIPATION ELASTICITY: " %6.3f `e_part'
di "  Standard error: " %6.3f `e_part_se'
di "  95% CI: [" %6.3f `e_part_lb' ", " %6.3f `e_part_ub' "]"

** Store for later use
scalar e_participation = `e_part'

** =============================================================================
** SECTION 4: Adjusted Elasticity (FT to PT Transitions)
** =============================================================================

di _n "=" * 70
di "ADJUSTED PARTICIPATION ELASTICITY (FT to PT)"
di "=" * 70

** Some part-time employment gains may come from full-time workers
** reducing hours, not non-workers entering employment.
** Adjustment: beta_adjusted = beta_PT + beta_FT

** Reload data to reset any changes
use if female == 1 & ///
       married == 0 & ///
       in_school == 0 & ///
       inrange(age, 20, 50) & ///
       citizen_test == 1 & ///
       inrange(year, 2012, 2017) ///
    using "${data}final/acs_working_file.dta", replace

keep if education <= 3
keep if state_status > 0

gen ca = (state_fips == 6)
gen post = (year >= 2015)
gen treated = (ca == 1 & qc_present == 1 & post == 1)
gen minwage = mean_st_mw

** Estimate effect on full-time employment
qui reghdfe full_time_y treated `state_controls' [aw = weight], ///
    absorb(`did' `controls') vce(cluster `clustervar')

local beta_ft = _b[treated]
local se_ft = _se[treated]

di "  DiD coefficient (full-time): " %8.5f `beta_ft' " (SE: " %8.5f `se_ft' ")"

** Adjusted beta: if FT decreases, that portion came from FT to PT, not NW to PT
local beta_adjusted = max(`beta_pt' + `beta_ft', 0)
di "  Adjusted beta (FT to PT): " %8.5f `beta_adjusted'

** Adjusted elasticity
local e_part_adj = (`beta_adjusted' / `P_base') / `denom'
di _n "  ADJUSTED PARTICIPATION ELASTICITY: " %6.3f `e_part_adj'

** =============================================================================
** SECTION 5: Elasticity with $27K Earnings Bin
** =============================================================================

di _n "=" * 70
di "ELASTICITY WITH $27K EARNINGS BIN ADJUSTMENT"
di "=" * 70

** Alternative adjustment: focus on full-time workers in $24K-$30K range
** These are workers who might reduce earnings to reach CalEITC kink

** CPI adjustment to 2017 dollars
qui summ cpi99 if year == 2017
local cpi_2017 = r(mean)
gen real_earnings = incearn * (cpi99 / `cpi_2017')

** Flag full-time workers in $27K bin
gen ft_27k = (full_time_y == 1 & inrange(real_earnings, 24001, 30000))
label var ft_27k "Full-time in $24K-$30K earnings bin"

** Estimate effect on FT in $27K bin
qui reghdfe ft_27k treated `state_controls' [aw = weight], ///
    absorb(`did' `controls') vce(cluster `clustervar')

local beta_ft27 = _b[treated]
local se_ft27 = _se[treated]

di "  DiD coefficient (FT $27K bin): " %8.5f `beta_ft27' " (SE: " %8.5f `se_ft27' ")"

** Adjusted beta using $27K bin
local beta_adj27 = max(`beta_pt' + `beta_ft27', 0)
di "  Adjusted beta ($27K bin): " %8.5f `beta_adj27'

** Elasticity with $27K adjustment
local e_part_27k = (`beta_adj27' / `P_base') / `denom'
di _n "  PARTICIPATION ELASTICITY ($27K adjustment): " %6.3f `e_part_27k'

** =============================================================================
** SECTION 6: Mobility Elasticity using TAXSIM
** =============================================================================

di _n "=" * 70
di "MOBILITY ELASTICITY CALCULATIONS (TAXSIM)"
di "=" * 70

** Mobility elasticity compares net-of-tax earnings at:
** 1. CalEITC kink point (part-time target)
** 2. Alternative work levels (full-time min wage or $27K)

** -----------------------------------------------------------------------------
** Step 6.1: Load CalEITC kink point parameters
** -----------------------------------------------------------------------------

di _n "Step 6.1: Loading CalEITC parameters"

import excel using "${data}eitc_parameters/caleitc_max_inc_max_cred.xlsx", ///
    clear firstrow

** Keep 2014 (pre) and 2017 (post) only
keep if inlist(tax_year, 2014, 2017)

** Rename for merge
rename tax_year year
rename qc_ct depx

** Save temporary file
tempfile caleitc_params
save `caleitc_params'

** -----------------------------------------------------------------------------
** Step 6.2: Calculate QC distribution weights
** -----------------------------------------------------------------------------

di _n "Step 6.2: Calculating QC distribution"

use if female == 1 & ///
       married == 0 & ///
       inrange(age, 20, 50) & ///
       in_school == 0 & ///
       citizen_test == 1 & ///
       education < 4 & ///
       year == 2017 & ///
       state_fips == 6 & ///
       qc_ct > 0 ///
    using "${data}final/acs_working_file.dta", replace

** Collapse to get QC shares
gen ct = 1
collapse (sum) ct [fw = weight], by(qc_ct)
egen total = total(ct)
gen share = ct / total
rename qc_ct depx

keep depx share
tempfile qc_shares
save `qc_shares'

di "  QC distribution:"
list depx share

** -----------------------------------------------------------------------------
** Step 6.3: Create TAXSIM input scenarios
** -----------------------------------------------------------------------------

di _n "Step 6.3: Creating TAXSIM scenarios"

clear

** 4 QC levels x 2 years x 3 work scenarios = 24 observations
set obs 24

** Generate identifiers
gen depx = floor(mod(_n - 1, 12) / 3)  // 0, 1, 2, 3
gen year = 2014 + (mod(_n - 1, 2) == 1) * 3  // 2014 or 2017
gen work = mod(_n - 1, 3) + 1  // 1, 2, 3

** Adjust: create proper structure
drop _all
set obs 4
gen depx = _n - 1  // 0, 1, 2, 3

** Expand for 2 years
expand 2
bysort depx: gen year = 2014 + (_n - 1) * 3

** Expand for 3 work scenarios
expand 3
bysort depx year: gen work = _n

** TAXSIM input variables
gen state = 5  // California
gen mstat = 1  // Single
gen page = 30  // Age 30

** Child ages (for QC assignment)
gen age1 = cond(depx >= 1, 6, 0)
gen age2 = cond(depx >= 2, 6, 0)
gen age3 = cond(depx >= 3, 6, 0)

** Merge with CalEITC kink points
merge m:1 year depx using `caleitc_params', keep(match master)
tab year _merge

** Initialize wages
gen pwages_scenario = 0

** Scenario 1: CalEITC kink point
replace pwages_scenario = pwages if work == 1

** Scenario 2: Full-time at 2017 minimum wage ($10.50/hr)
local ft_minwage = 10.50 * 40 * 52  // $21,840
replace pwages_scenario = `ft_minwage' if work == 2

** Scenario 3: Full-time at $27K (observed spike)
replace pwages_scenario = 27000 if work == 3

** Generate TAXSIM ID
gen taxsimid = _n

** Save pre-TAXSIM file
tempfile taxsim_input
save `taxsim_input'

** Prepare TAXSIM submission file
keep taxsimid year state mstat page depx age1 age2 age3 pwages_scenario
rename pwages_scenario pwages

** -----------------------------------------------------------------------------
** Step 6.4: Run TAXSIM
** -----------------------------------------------------------------------------

di _n "Step 6.4: Running TAXSIM"

** Save input file
cd "${data}taxsim"
save taxsim_input, replace
export delimited taxsim_input.csv, replace

** Run TAXSIM (requires taxsimlocal35 command)
capture noisily taxsimlocal35, full

** If TAXSIM fails, provide fallback message
if _rc != 0 {
    di as error "TAXSIM execution failed. Ensure taxsimlocal35 is installed."
    di as error "Install with: net install taxsimlocal35, from(https://taxsim.nber.org/stata)"
    cd "${dir}"
    log close log_04
    exit 198
}

** Load results
clear
import delimited results.raw

** Return to main directory
cd "${dir}"

** Clean up
destring taxsimid, replace force
drop if missing(taxsimid)

** Keep tax components
keep taxsimid fiitax siitax fica v10
rename v10 gross_wages
gen total_tax = fiitax + siitax + fica
gen net_earnings = gross_wages - total_tax

** Merge back scenario info
merge 1:1 taxsimid using `taxsim_input', nogen

** -----------------------------------------------------------------------------
** Step 6.5: Calculate net-of-tax earnings differentials
** -----------------------------------------------------------------------------

di _n "Step 6.5: Calculating earnings differentials"

** Keep needed variables
keep work year depx gross_wages total_tax net_earnings

** Reshape to wide by year
reshape wide total_tax gross_wages net_earnings, i(depx work) j(year)

** Reshape to wide by work scenario
reshape wide total_tax* gross_wages* net_earnings*, i(depx) j(work)

** Merge QC shares
merge 1:1 depx using `qc_shares', nogen

** Calculate differentials for mobility elasticity
** n_kink vs n_alt where alt is FT minwage (2) or $27K (3)

** Scenario 1: Kink vs FT minwage
gen diff_kink_ft_2017 = abs(net_earnings20171 - net_earnings20172)
gen diff_kink_ft_2014 = abs(net_earnings20141 - net_earnings20142)

** Scenario 2: Kink vs $27K
gen diff_kink_27k_2017 = abs(net_earnings20171 - net_earnings20173)
gen diff_kink_27k_2014 = abs(net_earnings20141 - net_earnings20143)

** Log differentials (denominator for mobility elasticity)
gen log_denom_ft = ln(diff_kink_ft_2017) - ln(diff_kink_ft_2014)
gen log_denom_27k = ln(diff_kink_27k_2017) - ln(diff_kink_27k_2014)

** Numerator: ln(P + beta) - ln(P)
gen log_numer_full = ln(`P_base' + `beta_pt') - ln(`P_base')
gen log_numer_partial = ln(`P_base' + abs(`beta_ft27')) - ln(`P_base')

** Mobility elasticities
gen e_mob_ft_full = log_numer_full / log_denom_ft
gen e_mob_27k_full = log_numer_full / log_denom_27k
gen e_mob_ft_partial = log_numer_partial / log_denom_ft
gen e_mob_27k_partial = log_numer_partial / log_denom_27k

** -----------------------------------------------------------------------------
** Step 6.6: Display mobility elasticity results
** -----------------------------------------------------------------------------

di _n "=" * 70
di "MOBILITY ELASTICITY RESULTS"
di "=" * 70

di _n "By QC count (weighted by sample distribution):"
table depx [aw = share], ///
    stat(mean e_mob_ft_full e_mob_27k_full e_mob_ft_partial e_mob_27k_partial)

** Weighted average
qui summ e_mob_ft_full [aw = share]
local e_mob_ft_full_avg = r(mean)

qui summ e_mob_27k_full [aw = share]
local e_mob_27k_full_avg = r(mean)

qui summ e_mob_ft_partial [aw = share]
local e_mob_ft_partial_avg = r(mean)

qui summ e_mob_27k_partial [aw = share]
local e_mob_27k_partial_avg = r(mean)

di _n "Weighted average mobility elasticities:"
di "  vs FT minwage (full effect): " %6.3f `e_mob_ft_full_avg'
di "  vs $27K (full effect): " %6.3f `e_mob_27k_full_avg'
di "  vs FT minwage (partial): " %6.3f `e_mob_ft_partial_avg'
di "  vs $27K (partial): " %6.3f `e_mob_27k_partial_avg'

** =============================================================================
** SECTION 7: Summary Table
** =============================================================================

di _n "=" * 70
di "SUMMARY OF ELASTICITY ESTIMATES"
di "=" * 70

di _n "PARTICIPATION ELASTICITIES:"
di "  Baseline (all NW to PT): " %6.3f `e_part'
di "  Adjusted (FT to PT): " %6.3f `e_part_adj'
di "  $27K bin adjustment: " %6.3f `e_part_27k'

di _n "MOBILITY ELASTICITIES:"
di "  vs FT minwage (full): " %6.3f `e_mob_ft_full_avg'
di "  vs $27K (full): " %6.3f `e_mob_27k_full_avg'
di "  vs FT minwage (partial): " %6.3f `e_mob_ft_partial_avg'
di "  vs $27K (partial): " %6.3f `e_mob_27k_partial_avg'

di _n "=" * 70

** =============================================================================
** End
** =============================================================================

clear
log close log_04
